[package]
name = "mina-conn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Client-side daemon connection and request plumbing for minae"

[dependencies]
mina-protocol = { path = "../mina-protocol", version = "0.0.4" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
libc.workspace = true